spring:
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.cnvhasxxvhsscrswklpg
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false