spring:
  datasource:
    url: jdbc:postgresql://db.cnvhasxxvhsscrswklpg.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false