spring:
  application:
    name: forum
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/forum_db'
    username: 'postgres'
    password: ${DB_PASSWORD}

api:
  security:
    token:
      secret: ${JWT_SECRET}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
